server:
  port: 8085
spring:
  application:
    name: api-gateway
    # product service route
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Địa chỉ Eureka Server
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true     # Khuyến khích dùng IP
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO


